POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjY5YzFhNTJkNWVkNTU5MTRhMWNiZTRiNiIsImlhdCI6MTc3NDM0ODQ5N30.MOQNHFnHVTFouXEeyXRFliwqRREPoQdy6s6Au3VBhS0

{
    "author": "New One",
    "title": "Kabbom",
    "url": "https://google.com",
    "likes": 67
}